// Source for deployed Supabase Edge Function: team-admin.
// Production version currently deployed: v4.
// Keep this file aligned with the deployed function when making future changes.

import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const SITE = Deno.env.get("APP_SITE_URL") || "https://www.homedesignlab.it";
const admin = createClient(URL, SERVICE, { auth: { persistSession:false, autoRefreshToken:false } });
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const MODULES=["progettazione","immobiliare","clienti","finanze","documenti","journal"];
const LEVELS=["none","view","edit","manage"];
const json=(status:number,body:unknown)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
const bearer=(req:Request)=>{const h=req.headers.get("Authorization")||"";return h.startsWith("Bearer ")?h.slice(7):null};
async function requireAdmin(req:Request){const t=bearer(req);if(!t)return json(401,{error:"Non autenticato"});const {data,error}=await admin.auth.getUser(t);if(error||!data.user)return json(401,{error:"Token non valido"});const {data:p}=await admin.from("operatori_profiles").select("id,user_id,ruolo_portale,accesso_attivo").eq("user_id",data.user.id).maybeSingle();const {data:lp}=await admin.from("profiles").select("role").eq("user_id",data.user.id).maybeSingle();if(p?.accesso_attivo===false)return json(403,{error:"Accesso sospeso"});if(p?.ruolo_portale!=="admin"&&lp?.role!=="admin")return json(403,{error:"Operazione riservata agli Admin"});return data.user;}
function norm(p:any){const s=p&&typeof p==="object"?p:{};const m=s.modules&&typeof s.modules==="object"?s.modules:{};const out:any={};for(const k of MODULES){const v=m[k];const x=typeof v==="string"?v:v?.level;out[k]=LEVELS.includes(x)?x:v===true?"view":"none"}return{portal_role:["admin","segreteria","collaboratore"].includes(s.portal_role)?s.portal_role:"collaboratore",accesso_attivo:s.accesso_attivo!==false,scope:["all","assigned","custom"].includes(s.scope)?s.scope:"assigned",modules:out}}
async function audit(actor:string,op:string|null,action:string,details:any={}){await admin.from("operator_audit_log").insert({operator_profile_id:op,actor_user_id:actor,action,details})}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{const actor=await requireAdmin(req);if(actor instanceof Response)return actor;const b=await req.json().catch(()=>({}));const action=b?.action;
if(action==="list"){const {data,error}=await admin.from("operatori_profiles").select("id,user_id,nome,cognome,email,telefono,data_nascita,luogo_nascita,ruolo,livello_accesso,permessi_dettagli,dati_fatturazione,progetti_assegnati,collaboratore_drive_folder_id,avatar_url,specializzazione,bio,accesso_attivo,ruolo_portale,created_at,updated_at").order("nome");if(error)throw error;const pr=await admin.from("projects").select("id,titolo").order("titolo");return json(200,{operators:data||[],projects:pr.data||[]})}
if(action==="create"){const d=b.data||{};const email=String(d.email||"").trim().toLowerCase();const nome=String(d.nome||"").trim();if(!nome||!email||!email.includes("@"))return json(400,{error:"Nome ed email sono obbligatori"});const p=norm(d.permessi_dettagli);const redirectTo=`${SITE.replace(/\/$/,"")}/attiva-account.html`;const {data:u,error:ie}=await admin.auth.admin.inviteUserByEmail(email,{data:{nome,cognome:d.cognome||null,portal_role:p.portal_role},redirectTo});if(ie)throw ie;if(!u.user)throw new Error("Utente Auth non creato");const legacyRole=p.portal_role==="admin"?"admin":"operator";await admin.from("profiles").upsert({user_id:u.user.id,nome,email,role:legacyRole,is_active:true},{onConflict:"user_id"});const row={...d,email,nome,user_id:u.user.id,permessi_dettagli:p,accesso_attivo:p.accesso_attivo,ruolo_portale:p.portal_role,ruolo:p.portal_role==="admin"?"admin":"operatore",created_at:new Date().toISOString(),updated_at:new Date().toISOString()};const {data:op,error:oe}=await admin.from("operatori_profiles").insert(row).select("id,user_id,nome,cognome,email,accesso_attivo,ruolo_portale").single();if(oe)throw oe;await audit(actor.id,op.id,"collaboratore_creato",{email,role:p.portal_role});return json(200,{ok:true,operator:op})}
if(!["save","toggle","change_email","reset_password"].includes(action))return json(400,{error:"Azione non supportata"});const id=b.operatorId;if(!id)return json(400,{error:"operatorId obbligatorio"});const {data:cur,error:ce}=await admin.from("operatori_profiles").select("*").eq("id",id).maybeSingle();if(ce)throw ce;if(!cur)return json(404,{error:"Collaboratore non trovato"});
if(action==="toggle"){const active=b.accesso_attivo!==false;const {error}=await admin.from("operatori_profiles").update({accesso_attivo:active,updated_at:new Date().toISOString()}).eq("id",id);if(error)throw error;await audit(actor.id,id,active?"accesso_riattivato":"accesso_sospeso");return json(200,{ok:true,accesso_attivo:active})}
if(action==="change_email"){const email=String(b.email||"").trim().toLowerCase();if(!cur.user_id)return json(409,{error:"Collaboratore non collegato ad Auth"});const {error}=await admin.auth.admin.updateUserById(cur.user_id,{email});if(error)throw error;const {error:de}=await admin.from("operatori_profiles").update({email,updated_at:new Date().toISOString()}).eq("id",id);if(de)throw de;await audit(actor.id,id,"email_modificata",{email});return json(200,{ok:true,email})}
if(action==="reset_password"){if(!cur.user_id)return json(409,{error:"Collaboratore non collegato ad Auth"});const {data,error}=await admin.auth.admin.generateLink({type:"recovery",email:cur.email,options:{redirectTo:`${SITE.replace(/\/$/,"")}/attiva-account.html`}});if(error)throw error;await audit(actor.id,id,"reset_password_generato");return json(200,{ok:true,action_link:data.properties?.action_link||null})}
const incoming=b.data&&typeof b.data==="object"?b.data:{};const p=norm(incoming.permessi_dettagli);const email=String(incoming.email??cur.email??"").trim().toLowerCase();if(cur.user_id&&email!==String(cur.email||"").trim().toLowerCase()){const {error}=await admin.auth.admin.updateUserById(cur.user_id,{email});if(error)throw error}const upd={...incoming,email,permessi_dettagli:p,accesso_attivo:p.accesso_attivo,ruolo_portale:p.portal_role,updated_at:new Date().toISOString()};delete upd.id;delete upd.user_id;const {error:ue}=await admin.from("operatori_profiles").update(upd).eq("id",id);if(ue)throw ue;await audit(actor.id,id,"profilo_modificato",{role:p.portal_role,active:p.accesso_attivo,modules:p.modules,scope:p.scope});return json(200,{ok:true})
}catch(e){if(e instanceof Response)return e;console.error(e);return json(500,{error:e?.message||"Errore interno"})}});
